---
- hosts: all
  become: true
  tasks:

  - name: install apache and php on Ubuntu
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache and php on Fedora
    ansible.builtin.command: dnf install -y {{ apache_package }} {{ php_package }}
    when: ansible_distribution == "Fedora"
