---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
      use_backend: dnf
    when: ansible_distribution == "Fedora"

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: create user
    tags: always
    ansible.builtin.user:
      name: simone
      group: root

  - name: add sudoers file for simone
    tags: always
    ansible.builtin.copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

  - name: add ssh key for simone user
    tags: always
    ansible.builtin.authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF2qNGbLlq7iv/guPsPMUdsVHcfRCejIeCqpzmqSgo4Y admin@ubuntu-ws"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache on web servers (Ubuntu)
    tags: apache,ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

  - name: install apache on web servers (fedora)
    tags: apache,fedora
    ansible.builtin.dnf:
      name: httpd
      use_backend: dnf  
    when: ansible_distribution == "Fedora"

  - name: ensure apache is running (ubuntu)
    tags: apache,ubuntu
    ansible.builtin.service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache is running (fedora)
    tags: apache,fedora
    ansible.builtin.service:
      name: httpd
      state: started
    when: ansible_distribution == "Fedora"

  - name: change email address for admin
    tags: apache,fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Fedora"
    register: httpd 

  - name: restart httpd (fedora)
    tags: apache,fedora
    ansible.builtin.service:
      name: httpd
      state: restarted
    when: httpd.changed 

  - name: copy html file for site
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    

- hosts: db_servers
  tags: db,fedora
  become: true
  tasks:
  - name: install mariadb on db servers
    ansible.builtin.dnf:
      name: mariadb
      state: latest
      use_backend: dnf
    when: ansible_distribution == "Fedora"
